server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin123@${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-serve
  security:
    user:
      name: admin
      password: admin123