server:
  port: 8762
#   port: 9999
  connectionTimeout: 20000
spring:
  application:
    name: service-hi
  redis:
    host: 192.168.1.140
    port: 6379
    database: 10
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
