server:
  port: 8762
#   port: 9999
  connectionTimeout: 20000
spring:
  application:
    name: service-hi
  redis:
    host: 192.168.1.140
    port: 6379
    database: 10
  data:
    mongodb:
      host: 192.168.1.3
      port: 27017
      database: test
      authenticationDatabase: admin
      username: test
      password: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
#aws:
#  accessKey: username  #账号
#  secretKey: Password  #密码
#  serviceEndpoint: http://192.168.1.1 #地址
#  bucketName: name #桶名称