server:
  port: 8762
#   port: 9999
  connectionTimeout: 20000
spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
