server:
  port: 8762
  #   port: 9999
  connectionTimeout: 20000
spring:
  application:
    name: service-hi
  redis:
    host: 192.168.1.140
    port: 6379
    database: 10

  data:
    mongodb:
      host: 192.168.1.3
      port: 27017
      database: test
      authenticationDatabase: admin
      username: test
      password: test
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: true
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.190:32769
      bindings:
        input:
          destination: out-test
        out:
          destination: out-test



#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:admin123@localhost:8761/eureka/

apollo:
  bootstrap:
    enabled: true
  plugin:
    namespace: yangpeng-test


#aws:
#  accessKey: username  #账号
#  secretKey: Password  #密码
#  serviceEndpoint: http://192.168.1.1 #地址
#  bucketName: name #桶名称