server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: httpbin
          uri: http://httpbin.org:80/get
          predicates:
            - Path=/163/**  #断言，复合这个条件才转发到指定URL

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
